spring:
  main:
    banner-mode: OFF

  jpa:
    show-sql: false

  kafka:
    consumer:
      auto-offset-reset: earliest
    listener:
      ack-mode: manual

app:
  outbox:
    poll-ms: 100
    batch-size: 20
    max-retries: 3

logging:
  level:
    root: INFO
    com.codechallenge.loginprocessingservice: DEBUG
    org.apache.kafka: WARN
    org.springframework.kafka: INFO
    org.springframework.test.context: INFO
    io.github.resilience4j.retry: WARN
